### ISSUE TITLE
ADB-QR: Invalid port while parsing address

### ISSUE THREAD

**Issue by zanovis** [aakash-pamnani/ADB-QR#10] opened 2023-07-16 03:07 UTC
Getting this error when trying to connect via QR/Pairing Code on Windows 10. System ENV variable set for ADB

**Comment by aakash-pamnani** [comment] 2023-07-17 04:55
Can you share the adb version you have installed and android version of your device.

**Comment by zanovis** [comment] 2023-07-22 21:27
Android Debug Bridge version 1.0.41
Version 34.0.4-10411341

**Comment by gokuls1999** [comment] 2023-09-12 08:53
I am also getting the same error in macbook ADB-QR: Invalid port while parsing address [fe80::3c47:8dff:feaf:f759:38507]

**Comment by Safius-Sifat** [comment] 2023-09-13 13:36
Hey, I am also facing the same issue. My adb version--
Android Debug Bridge version 1.0.41
Version 34.0.4-10411341

**Comment by aakash-pamnani** [comment] 2023-09-13 19:12
open vscode > ctrl+shift+p > "Developer: Toggle Developer Tools"

Then try to connect with QR/Pairing code

After the error, Share the logs from the developer console window.

**Comment by gokuls1999** [comment] 2023-09-15 05:33
<img width="654" alt="image" src="https://github.com/aakash-pamnani/ADB-QR/assets/93990920/f0958f2e-c016-4a1a-9d2a-904589639d01">

Iam also getting same issue. I am trying to connect using pair code. Here is the log from developer console

**Comment by aakash-pamnani** [comment] 2023-09-15 07:07
@gokuls1999 thanks for sharing logs,
The problem is due to ipv6 address,
This may be due to your mobile data is turned on or your wifi router is using ipv6?

**Comment by JVimes** [comment] 2023-10-15 20:51
@aakash-pamnani Can you parse or skip the v6 address?

**Comment by aakash-pamnani** [comment] 2023-10-16 05:26
> @aakash-pamnani Can you parse or skip the v6 address?

Yes I am working on it, but it will take some time.

**Comment by legallyfree** [comment] 2023-11-13 15:30
Hello,

What I do is deactivate the Firewalld that my Arch Linux system has,
Then I turn on the wireless treatment plant,
active the link with synchronization code,
Then in console outside the vscode I write:
`> adb pair 192.168.xx.xxx:port 463604`
then from vscode I use the extension ADB QR Connect with Paired Devices
Only in this way, it connects,
With the Firewalld, try to open the ports that ADB uses from version 11 with the range 30000-4999,
`> sudo firewall-cmd --add-port=30000-49999/tcp --permanent `
But it doesn't work for me and the easy way is to stop the Firewalld.
Something that never worked for me is with the QR, With the Firewalld deactivated inclusive.
Then I see that my problem is the Firewalld but I do not know how to solve it and just stopping it I can connect it.
So the extension works correctly and is the configuration of each distribution with its safety is what makes it fail when connecting. 
Some tried to deactivate your firewall, surely with UFW that is easier is more permissive with connections 🤔

Now updated my area home and without closing the Firewalld it connects normally, 
it was previously as a public area 🥲

**Comment by aakash-pamnani** [comment] 2023-12-14 11:35
@zanovis @Safius-Sifat @gokuls1999 @JVimes update to latest version and let me know if the problem still persist.

**Comment by JVimes** [comment] 2023-12-14 20:37
@aakash-pamnani I don't get "invalid port" today, thank you!

**Closed as completed** 2023-12-27 14:19 UTC
